USE PrestigeCarsNorm

-- COUNTRY
CREATE TYPE UDT_CountryID FROM INT;
CREATE TYPE UDT_CountryName FROM NVARCHAR(150);
CREATE TYPE UDT_CountryISO2 FROM NCHAR(10);
CREATE TYPE UDT_CountryISO3 FROM NCHAR(10);
CREATE TYPE UDT_Region FROM NVARCHAR(20);

-- MAKE
CREATE TYPE UDT_MakeID FROM INT;
CREATE TYPE UDT_MakeName FROM NVARCHAR(100);
CREATE TYPE UDT_MakeCountry FROM CHAR(3);

-- MODEL
CREATE TYPE UDT_ModelID FROM INT;
CREATE TYPE UDT_ModelName FROM NVARCHAR(150);
CREATE TYPE UDT_ModelVariant FROM NVARCHAR(150);
CREATE TYPE UDT_Year FROM CHAR(4);

-- CUSTOMER
CREATE TYPE UDT_CustomerID FROM NVARCHAR(5);
CREATE TYPE UDT_CustomerName FROM NVARCHAR(150);
CREATE TYPE UDT_Address FROM NVARCHAR(50);
CREATE TYPE UDT_CountryRef FROM INT;
CREATE TYPE UDT_IsReseller FROM BIT;
CREATE TYPE UDT_IsCreditRisk FROM BIT;

-- STOCK
CREATE TYPE UDT_StockCode FROM NVARCHAR(50);
CREATE TYPE UDT_ModelRef FROM SMALLINT;
CREATE TYPE UDT_ColorID FROM INT;
CREATE TYPE UDT_Cost FROM MONEY;
CREATE TYPE UDT_RepairsCost FROM MONEY;
CREATE TYPE UDT_PartsCost FROM MONEY;
CREATE TYPE UDT_TransportCost FROM MONEY;
CREATE TYPE UDT_BuyerComments FROM NVARCHAR(4000);
CREATE TYPE UDT_DateBought FROM DATE;
CREATE TYPE UDT_TimeBought FROM TIME(7);

-- SALES
CREATE TYPE UDT_SalesID FROM INT;
CREATE TYPE UDT_InvoiceNumber FROM CHAR(8);
CREATE TYPE UDT_SaleDate FROM DATETIME;
CREATE TYPE UDT_TotalSalePrice FROM NUMERIC(18,2);

-- SALES DETAILS
CREATE TYPE UDT_LineItemNumber FROM TINYINT;
CREATE TYPE UDT_SalePrice FROM NUMERIC(18,2);
CREATE TYPE UDT_LineItemDiscount FROM NUMERIC(18,2);